paths:
  /api/products:
    get:
      summary: Get all products
      tags:
      - Products
      description: Returns a list of all products.
      operationId: getAllProducts
      responses:
        '200':
          description: A JSON array of products
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    price:
                      type: number
                    description:
                      type: string

    post:
      summary: Create a new product
      tags:
      - Products
      description: Creates a new product.
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                description:
                  type: string
      responses:
        '201':
          description: Product successfully created
        '400':
          description: Invalid input

  /api/products/mock:
    get:
      summary: Get mocking products
      tags:
      - Products
      description: Returns a list of mock products for testing.
      operationId: getMockingProducts
      responses:
        '200':
          description: A JSON array of mock products
          content:
            application/json:
              schema:
                type: array
                items: 
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    price:
                      type: number
                    description:
                      type: string

  /api/products/{pid}:
    get:
      summary: Get product by ID
      tags:
      - Products
      description: Returns a product by its ID.
      operationId: getProductById
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A product object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  price:
                    type: number
                  description:
                    type: string
        '404':
          description: Product not found

  /api/products/{id}:
    delete:
      summary: Delete product by ID
      tags:
      - Products
      description: Deletes a product by its ID.
      operationId: deleteProductById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product successfully deleted
        '404':
          description: Product not found

    put:
      summary: Update product by ID
      tags:
      - Products
      description: Updates a product by its ID.
      operationId: updateProductById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                description:
                  type: string
      responses:
        '200':
          description: Product successfully updated
        '400':
          description: Invalid input
        '404':
          description: Product not found